services:
  anime-mysql:
    image: mysql:8.0.39
    container_name: anime-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  anime-server:
    container_name: anime-server
    build:
      context: ./anime-server
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: mysql://root:rootpassword@anime-mysql:3306/animeDatabase
    networks:
      - frontend
      - backend
    ports:
      - "5001:5001"
    depends_on:
      - anime-mysql
    volumes:
      - ./anime-server:/app

  anime-client:
    container_name: anime-client
    build:
      context: ./anime-client
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:5001
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./anime-client:/app
      - /app/node_modules
    depends_on:
      - anime-server
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  mysql_data:
